config/routes.rb
Revive2::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'pages#home'
  get '/help' => 'pages#help'
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  get '/alterations' => 'pages#alterations'
  get '/garment_repair' => 'pages#garment_repair'
  get '/footwear_repair' => 'pages#footwear_repair'
  get '/leather_repair' => 'pages#leather_repair'
  get '/measurement_fit' => 'pages#measurement_fit'
  get '/quality_garments' => 'pages#quality_garments'
  get '/quality_footwear' => 'pages#quality_footwear'
  get '/careers' => 'pages#careers'
  get '/faq' => 'pages#faq'
  get '/returns' => 'pages#returns'
  get '/privacy' => 'pages#privacy'

  resource :shopping_cart
  resources :shopping_cart_items, only: [ :destroy ]
  devise_for :users

  resources :products 
  resources :orders

  Category.all.each do |i|
    resources i.symbolize, controller: 'products', type: i.name do

  end
end
  namespace :admin do
  Category.all.each do |i|
    resources i.symbolize, controller: 'products', type: i.name
  end
end
 

  

end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
    acts_as_shopping_cart
    
    def tax_pct
	0
    end
    def self.has_product?(item_id,cart_id)
		ShoppingCartItem.where("owner_id=? AND item_id=?",cart_id,item_id).present?
    end
    def total_cents
    	(total*100).floor
    end
   
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_filter :extract_shopping_cart, except: [:destroy]

  def create
    @product = Product.find(params[:product_id])
    @shopping_cart.add(@product, @product.price)
    respond_to do |format|
      format.html {redirect_to shopping_cart_path}
      format.js
    end
  end

  def show

  end

  def destroy
  #shopping_cart_id = session[:shopping_cart_id]
  #@shopping_cart = ShoppingCart.find(shopping_cart_id)
  #@shopping_cart.clear
  @shopping_cart.clear
  redirect_to { products_path }

  end

  private
  def extract_shopping_cart
    @shopping_cart = current_cart
   
  end
end

app/views/shopping_carts/_shopping_cart_item.html.erb
<tr id="carted_item_<%=shopping_cart_item.item.id%>"class="<%= shopping_cart_item.nla? ? "danger" : "" %>">
	<td>
		<%= link_to image_tag(shopping_cart_item.item.uploads.first.uploaded_file(:thumb)), product_path(shopping_cart_item.item) %>
	</td>
	<td>
		<strong><%= shopping_cart_item.item.brand %></strong>
		<br />
		<%= shopping_cart_item.item.description %>
		<br />
		<%= shopping_cart_item.item.size %>
		<br />

	</td>
	<td><%= shopping_cart_item.nla? ? "Sold Out" : number_to_currency(shopping_cart_item.item.price) %>
	<%= link_to "x", shopping_cart_item, method: :delete, remote: true, :class=>"close" if controller.controller_name=="shopping_carts"%></td>
	
</tr>

app/views/shopping_carts/_shopping_cart_totals.html.erb
<tr><td></td><td>Subtotal:</td><td id="subtotal"><%=number_to_currency(@shopping_cart.subtotal)%></td></tr>
<tr><td></td><td>Taxes:</td><td id="taxes"><%=number_to_currency(@shopping_cart.taxes)%></td></tr>
<tr><td></td><td>Shipping:</td><td id="shipping">FREE</td></tr>
<tr><td></td><td>Total:</td><td id="total"><%=number_to_currency(@shopping_cart.total)%></td></tr>

app/views/shopping_carts/create.js.erb
//$('#AddToCartNotice').modal(
//	keyboard: true
//	);
$('#CartCount').replaceWith('<span id="CartCount"><%= j "(#{count_shopping_cart_items}) "%></span>');
$('#purchasing').replaceWith('<%= j render "products/show/purchasing"%>');

app/views/shopping_carts/show.html.erb
<h1>Shopping Cart</h1>
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12">
<table class="table table-striped">
<tbody>
<%= render :partial => 'shopping_cart_item', :collection => @shopping_cart.shopping_cart_items %>
</tbody>
<tfoot id="cartTotals">
<%= render :partial => 'shopping_carts/shopping_cart_totals' %>
<tr>
<td></td>
<td></td>
<td>
<%= link_to "Checkout", new_order_path, class: "btn btn-lg btn-default" %>
</td>
</tr>

</tfoot>
</table>
</div>
</div>