config/routes.rb
Revive2::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'pages#home'
  get '/help' => 'pages#help'
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  get '/alterations' => 'pages#alterations'
  get '/garment_repair' => 'pages#garment_repair'
  get '/footwear_repair' => 'pages#footwear_repair'
  get '/leather_repair' => 'pages#leather_repair'
  get '/measurement_fit' => 'pages#measurement_fit'
  get '/quality_garments' => 'pages#quality_garments'
  get '/quality_footwear' => 'pages#quality_footwear'
  get '/careers' => 'pages#careers'
  get '/faq' => 'pages#faq'
  get '/returns' => 'pages#returns'
  get '/privacy' => 'pages#privacy'

  resource :shopping_cart
  resources :shopping_cart_items, only: [ :destroy ]
  devise_for :users

  resources :products 
  resources :orders

  Category.all.each do |i|
    resources i.symbolize, controller: 'products', type: i.name do

  end
end
  namespace :admin do
  Category.all.each do |i|
    resources i.symbolize, controller: 'products', type: i.name
  end
end
 

  

end

app/views/partials/_account.html.erb
    <% if user_signed_in? %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <span class="glyphicon glyphicon-user"></span>
        Account
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to edit_user_registration_path do %>
          <span class="glyphicon glyphicon-cog"></span>
          Edit Account Info
          <% end %>
        </li>
        <li class="divider"></li>
        <li><a href="#"><span class="glyphicon glyphicon-stats"></span>
        Size Preferences</a></li>
        <li class="divider"></li>
        <li><%= link_to orders_path do %>
         <span class="glyphicon glyphicon-heart"></span>
         Orders
         <% end %></li>
         <li class="divider"></li>
         <li><a href="#"><span class="badge"> 1 </span>
         Special Offers
         </a></li>
         <li class="divider"></li>

         <li><%=link_to destroy_user_session_path, method: :delete do%>
          <span class="glyphicon glyphicon-log-out pull-right"></span>
          Log Out
          <% end %>
        </li>
      </ul>
    </li>
    <% else %>
    <li>
    <button class="btn btn-link" data-toggle="modal" data-target=".bs-modal-sm">Login</button>
    </li>
    <%= render 'partials/login' %>

    <% end %>

app/views/partials/_breadcrumbs.html.erb
  <div class="row breadcrumbs">
    <div class="col-md-12">
      <%= render_breadcrumbs %>
    </div>
  </div>

app/views/partials/_footer.html.erb
<footer>
	<div class="container footer">
		<div class="row">
			<ul class="list-inline">
					<li><a href="/about">About</a></li>
					<li><a herf="/careers">Careers</a></li>
				
					<li><a href="/contact">Contact Us</a></li>
				
					<li><a href="/help">Help</a></li>
					<li><a href="/faq">FAQ</a></li>
					<li><a href="#">My Account</a></li>
					<li><a href="/orders">Orders</a></li>
					<li><a href="#">Returns</a></li>
					<li><a href="#">Privacy Policy</a></li>
				</ul>
				
				<div class="pull-left">&copy;2014 Supero, LLC. All Rights Reserved</div>
		</div>

	</div>
</footer>

app/views/partials/_large_carousel.html.erb
	<div class="row hidden-xs">
	<div class="large-carousel">
	<div id="myCarousel" class="carousel slide">
		<div class="carousel-inner">
		    <div class="item active">
			<%=image_tag("remade.jpg")%>
				<div class="container">
					<div class="carousel-caption">
						<h1>Re-made to Measure</h1>
						<p class="lead">Tired of paying a bunch of money for shirts that <i>still</i> don't fit exactly right? One of our most popular options is our <strong>Re-made to Measure</strong> program. You get a high quality re-claimed garment that's been re-cut to fit you perfectly for less than a new shirt that doesn't even fit!
						</p>
						<a class="btn btn-large btn-default" href="#">Learn More</a>
					</div>
				</div>
			</div>
			<div class="item">
			    <%=image_tag("handmades.jpg")%>
				<div class="container">
					<div class="carousel-caption">
						<h1>Handmade Neckwear</h1>
						<p class="lead">After re-claiming cloth of the highest quality from destroyed garments, our skilled artisans hand craft new neckwear. Bias cut and finished with a single slip stitch that runs the entire length of the tie, our neckwear is top quality.
						</p>
						<a class="btn btn-large btn-default" href="#">Shop Now</a>
					</div>
				</div>
			</div>
			<div class="item">
			    <%=image_tag("packages.jpg")%>
				<div class="container">
					<div class="carousel-caption">
						<h1>Complete Outfit Packages</h1>
						<p class="lead">Big interview or promotion? Need it all and don't know where to start? We offer complete outfit packages to get you off to a great start from just $149 (tailored, out the door).
						</p>
						<a class="btn btn-large btn-default" href="#">Browse Packages</a>
					</div>
				</div>
			</div>
		</div>
	 <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
	</div><!-- /.carousel -->
	</div>
	</div>

app/views/partials/_list_group_item.html.erb
<li class="list-group-item"></span><a href="#"><%=list_group_item%></a></li>

app/views/partials/_login.html.erb
<div class="modal fade bs-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="login" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
       <ul id="myTab" class="nav nav-tabs">
			<li class="active"><a href="#signin" data-toggle="tab">Sign In</a></li>
        	<li><a href="#signup" data-toggle="tab">Register</a></li>
        </ul>
        <div class="modal-body">
	        <div id="myTabContent" class="tab-content">
	        
	        	<div class="tab-pane fade active in" id="signin">
		       <%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
			       <%= f.input :email, :required => false, :autofocus => true, placeholder: "email", label: false %>
			       <%= f.input :password, :required => false, placeholder: "password", label: false %>
			       <%= f.input :remember_me, :as => :boolean if devise_mapping.rememberable? %>
			       <%= f.button :submit, "Sign in" %>
		       <% end %>
		    	</div>

	        	<div class="tab-pane fade" id="signup">
	          <%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f|%>
		          <%= f.input :email, :required => true, :autofocus => true, placeholder: "email", label: false %>
		          <%= f.input :password, :required => true, placeholder: "password", label: false %>
		          <%= f.input :password_confirmation, :required => true, placeholder: "confirm password", label: false%>
		          <%= f.button :submit, "Sign up" %>
	          <% end %>
				</div>

	      	</div>
	  	</div>

      <div class="modal-footer">
	      <center>
	      	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	      </center>
      </div>

    </div>
  </div>
</div>

app/views/partials/_main_nav.html.erb
<div id="main_nav">
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main_nav_collapse">
      <span class="sr-only">Toggle navigation</span>
     
        <p class="navbar-text visible-sm visible-xs">Navigation</p>

    </button>

    <div class="collapse navbar-collapse" id="main_nav_collapse">

      <div class="navbar-inner center">

        <ul class="nav navbar-nav">
          <%= render :partial => "partials/nav_buttons/featured"%>
          <%= render :partial => "partials/nav_buttons/clothing"%>
          <%= render :partial => "partials/nav_buttons/footwear"%>
          <%= render :partial => "partials/nav_buttons/accessories"%>
          <%= render :partial => "partials/nav_buttons/services"%>
          <%= render :partial => "partials/nav_buttons/guides"%>
        </ul>
      </div>
    </div>
  </div>
</nav>
</div>

app/views/partials/_nav_button.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=nav_button%></a>
  <ul class="dropdown-menu">
    <li class="text-left"><a href="#">Example</a></li>
    <li class="text-left"><a href="#">Aligninment options</a></li>
    <li class="text-left"><a href="#">Headers</a></li>
    <li class="text-left"><a href="#">Disabled menu items</a></li>
  </ul>
</li>

app/views/partials/_product.html.erb
<div class="product-individual-container">
	<%= link_to product_path(product) do %>
	<%= image_tag product.thumb, class: "product-list-image img-responsive"%>
	<% end %>
	<div class="product-list-description">
	<%="#{product.brand.try(:titleize)} - #{product.size}"%><br />
	<%=number_to_currency(product.price)%>
	<%= "NEW ARRIVAL" if product.new_arrival?%>
	</div>
</div>

app/views/partials/_side_nav.html.erb
<div class="panel-group" id="sideNav">
  <div class="panel panel-default">

<%= render :partial => 'partials/top_side_nav_accordian', :collection => Category.all %>
</div>
</div>

app/views/partials/_side_nav_accordian.html.erb
<div class="panel-group" id="<%=parent%><%=name%>Accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h6 class="panel-title">
      <a data-toggle="collapse" data-parent="#<%=parent%><%=name%>Accordion" href="#collapse<%=parent%><%=name%>">
        </span><%=name.titleize%></a>
      </h6>
    </div>
    <div id="collapse<%=parent%><%=name%>" class="panel-collapse collapse">
      <ul class="list-group">
      <%= render :partial=>"partials/list_group_item", :collection => parent.constantize.send(name.pluralize) %>
     
      </ul>
    </div>
  </div>
</div>

app/views/partials/_small_carousel.html.erb
<div id="tS1" class="jThumbnailScroller" style="margin-top:160px;">
  <div class="jTscrollerContainer">
    <div class="jTscroller">
    <% @product.uploads.each do |upload| %>
        <%=image_tag(upload.uploaded_file(:thumb), :class=>"thumb")%>
      <% end %>
      
    </div>
  </div>
 
</div>
<%=link_to "supersize image", image_path(@product.main_photo), :id=>"link_to_change", :class=>"pull-right", :data => { :colorbox => true, :colorbox_max_width=> "100%", :colorbox_max_height => "100%" }%>

<script>

(function($){
window.onload=function(){
    $("#tS1").thumbnailScroller({
        scrollerType:"hoverPrecise",
        scrollerOrientation:"horizontal",
        scrollSpeed:2,
        scrollEasing:"easeOutCirc",
        scrollEasingAmount:600,
        acceleration:4,
        scrollSpeed:800,
        noScrollCenterSpace:10,
        autoScrolling:0,
   	});
}
})(jQuery);

</script>

app/views/partials/_top_nav.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!--  and toggle get grouped for better mobile display -->

    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-header-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-header-collapse">
      <div class="navbar-inner navbar-right">

        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>

        <ul class="nav navbar-nav navbar-right">
          <li>
            <%=link_to shopping_cart_path do %>
              <span class="glyphicon glyphicon-shopping-cart"></span>
              <span id="CartCount">&nbsp;<%="(#{count_shopping_cart_items})"%></span>
            <%end%>
          </li>
        <%= render 'partials/account' %>

        </ul>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_top_side_nav_accordian.html.erb
<div class="panel-group" id="<%=top_side_nav_accordian.name%>Accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h5 class="panel-title">
      <div data-toggle="collapse" data-parent="#<%=top_side_nav_accordian.name%>Accordion" href="#collapse<%=top_side_nav_accordian.name%>">
        <a id="<%=top_side_nav_accordian.name%>" href="/<%=top_side_nav_accordian.symbolize%>"><%=top_side_nav_accordian.display_name%></a>
        </div>
      </h5>
    </div>
    <div id="collapse<%=top_side_nav_accordian.name%>" class="panel-collapse collapse">

    <%= render partial: 'partials/side_nav_accordian', locals: {parent: top_side_nav_accordian.name, name: "size"} %>
    <%= render partial: 'partials/side_nav_accordian', locals: {parent: top_side_nav_accordian.name, name: "colors"} %>
    <%= render partial: 'partials/side_nav_accordian', locals: {parent: top_side_nav_accordian.name, name: "styles"} %>


    </div>
  </div>
</div>
<script>
$("#<%=top_side_nav_accordian.name%>").click(function(e) {
  e.stopPropagation();
});
</script>